version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - misspell
    - unconvert
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
  exclusions:
    paths:
      - web/dist

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/0funct0ry/ditty
